name: project build

on:
  push:
    branches: 
      - master

jobs:
  build-debug:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
        
      - name: install cocoapods
        run: gem install cocoapods
        
      - name: test
        run: |
          xcodebuild --help
          pod --version

