name: project build

on:
  push:
    branches: 
      - master

jobs:
  setup-dev:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
        
      - name: setup cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: latest
   
      - name: setup carthage
        run: brew install carthage

  build-debug: 
    runs-on: macos-latest
    needs: [setup-dev]
    steps:
      - name: test
        run: |
          xcodebuild --help
          pod --version

