name: project build

on:
  push:
    branches: 
      - master

jobs:
  setup-dev:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
          registry-url: https://registry.npmjs.org/

      - name: setup xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
        
      - name: setup cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: latest
   
      - name: setup carthage
        run: brew install carthage
  
  install:
    runs-on: macos-latest
    needs: [setup-dev]
    steps:
      - name: install npm-check-updates
        run: npm install -g npm-check-updates
        
      - name: install @fht360/fht-react-native
        run: npm run update
      
      - name: install pods
        run: pod install --repo-update
      
      - name: install carthage
        run: carthage update --platform iOS

  build-debug: 
    runs-on: macos-latest
    needs: [setup-dev, install]
    steps:
      - name: test
        run: |
          xcodebuild --help
          pod --version
          carthage version


