name: project build

on:
  push:
    branches: 
      - master

jobs:
  build-debug:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
          registry-url: https://registry.npmjs.org/
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: setup xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '11.5'
          apple-id: 'fht360@fht360,com'
          apple-id-password: ${{secrets.APPLE_ID_PASSWORD}}
        
      - name: setup cocoapods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: latest

      - name: Cache cocoapods
        uses: actions/cache@v2
        env:
          cache-name: cache-cocoa-pods
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.cocoapods
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
   
      - name: setup carthage
        run: brew install carthage
  
      - name: install npm-check-updates
        run: npm install -g npm-check-updates
        
      - name: install @fht360/fht-react-native
        run: npm run update
      
      - name: install pods
        run: pod install --repo-update
      
      - name: install carthage
        run: carthage update --platform iOS
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          GITHUB_ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: build debug
        run: xcodebuild build -workspace actions-test.xcworkspace -scheme actions-test -allowProvisioningUpdates -configuration Debug
      
      - name: build release
        run: xcodebuild build -workspace actions-test.xcworkspace -scheme actions-test -allowProvisioningUpdates -configuration Release


