name: project build

on:
  push:
    branches: 
      - master

jobs:
  build-debug: 
    runs-on: macos-latest
    steps:
      - name: test
        run: |
          xcodebuild --help
          pod --version
          carthage version


